using System;

public enum GoalType
{
	EMPTY,
	//
	PROPERTY_PLAYER_LEVEL,
	PROPERTY_YINPIAO_ACCUMULATE,
	PROPERTY_HERO_COUNT,
	PROPERTY_HERO_LEVEL_MAX,
	PROPERTY_HERO_SPELL_LEVEL_SUM,
	PROPERTY_HERO_FIGHT_POWER_SUM,
	PROPERTY_SPACE_WIN_COUNT,
	PROPERTY_ENTER_GUILD,
	PROPERTY_PRIVATE_SHARE_SPACE_ENTER,
	PROPERTY_PRIVATE_SHARE_SPACE_KILL,
	PROPERTY_VISIT_OTHER_HOME,
	PROPERTY_HOME_GOAL_COUNT,
	PROPERTY_PLAY_HERO_KID,
	PROPERTY_CD_GIFT,
	PROPERTY_LUCK_LOOT_COUNT,
	PROPERTY_DISCOVER_SPACE_EVENT,
	PROPERTY_DISCOVER_SPACE_BOSS,
	PROPERTY_FAKE_ARENA_WIN_COUNT,
	//
	HUNTER_SPACE_WIN,
	HUNTER_BUY_POWER,
	HUNTER_BUY_YINPIAO,
	HUNTER_FAKE_ARENA,
	HUNTER_LUCK_LOOT,
	HUNTER_CHAT,
	HUNTER_PRIVATE_SHARE_SPACE_CREATE,
	HUNTER_PRIVATE_SHARE_SPACE_ENTER,
	HUNTER_PRIVATE_SHARE_SPACE_KILL,
	HUNTER_VISIT_OTHER_HOME,
	HUNTER_HOME_GOAL_COUNT,
	HUNTER_PLAY_HERO_KID,
	HUNTER_CD_GIFT,
	HUNTER_HERO_SPELL,
	HUNTER_HERO_WEAPON,
	HUNTER_HERO_LEVEL,
	HUNTER_ITEM_USE,
	HUNTER_HERO_XPSTONE,
	HUNTER_HERO_KID_XPSTONE,
	HUNTER_RESPONSE,
	HUNTER_DISCOVER_SPACE_BUILDING,
	HUNTER_DISCOVER_SPACE_BOSS,

    HUNTER_KILL_NPC,
    HUNTER_TALK_TO_NPC,
    HUNTER_COLLECT_SPACE_OBJECT,
    HUNTER_OPEN_FUNCTION_UI,
    HUNTER_JUMP_SPACE,
    //
    TOTAL,
};

public enum GoalState
{
	UN_COMPLETE,
	COMPLETE,
	FAIL,
    CLICK_REWARD,
}

public enum GoalCategory
{
    MAINLINE = 0,// 主线

    BRANCHLINE,//支线
    ACTIVITY,//活动
    WEEKLY,//周常
    ORIENTATION,//定向

    TEAM,//组队
    TRANSFER,//转职
    LOVE,//情缘
    ADVENTURER,//冒险者
    UNION,//盟
}

public enum GoalStateType
{
    UnAcceptable,//不可接任务,（主线都可接，其他类型等级不够或者功能未开启）
    Acceptable,//可接任务
    UnderWay,//进行中
    CanReceive,//可领取奖励
    Finishi,//任务结束，完成或失败
}
public enum GoalCompleteIDMatchType
{
	NPC,
	SPACEOBJ,
	ITEM,
	GAMEFUNC,
	STORY,
    SPACE,
};
public enum GoalTurnInType
{
    AUTO,
    CLICK,
    TARGETNPC,
};