using System;

public enum CellPlayerClientMethod
{
	INF = 0,
	METHOD_0_MessageBox = INF,
	METHOD_1_DebugMessage,
	METHOD_2_ContainReserveWord,
	METHOD_3_OnPing,
	METHOD_4_HoldHeroRes,
	METHOD_5_FreeHeroRes,
	METHOD_6_OnNavigateTo,
	SUP,
}
public enum CellPlayerServerMethod
{
	INF = 0,
	METHOD_0_Exec = INF,
	METHOD_1_Exec,
	METHOD_2_OnPing,
	METHOD_3_UpdatePropertyWatcher,
	METHOD_4_SetHoldCallback,
	METHOD_5_OnClientStart,
	METHOD_6_OnClientEnd,
	METHOD_7_OnNewDay,
	METHOD_8_OnNewWeek,
	METHOD_9_OnNewMonth,
	METHOD_10_PrintProperty,
	METHOD_11_PrintCenterProperty,
	METHOD_12_PrintCenterComponentProperty,
	METHOD_13_PrintHeroProperty,
	METHOD_14_PrintSpaceProperty,
	METHOD_15_PrintSpaceFactionProperty,
	METHOD_16_PrintNPCProperty,
	METHOD_17_PrintGlobalProperty,
	METHOD_18_CopyPropertyFromFocus,
	METHOD_19_SpaceExec,
	METHOD_20_SpaceFactionExec,
	METHOD_21_EnterPublicSpace,
	METHOD_22_EnterPrivateSpace,
	METHOD_23_ExitSpace,
	METHOD_24_UpdateSpaceLoadProgress,
	METHOD_25_CompleteSpaceLoad,
	METHOD_26_OnSpaceCloseByGM,
	METHOD_27_REQ_SpaceScriptEvent,
	METHOD_28_SpaceSpell,
	METHOD_29_SpaceSpell,
	METHOD_30_ChatScriptBegin,
	METHOD_31_ChatScriptEnd,
	METHOD_32_ChatScriptShowItem,
	METHOD_33_ChatScriptWatchItem,
	METHOD_34_ChatMessage,
	METHOD_35_ChatMessage,
	METHOD_36_ClearHero,
	METHOD_37_CreateHero,
	METHOD_38_CompleteHeroLoad,
	METHOD_39_REQ_AddMoveSpeedScale,
	METHOD_40_REQ_DelMoveSpeedScale,
	METHOD_41_REQ_MoveTo,
	METHOD_42_REQ_MoveTo,
	METHOD_43_REQ_BreakMoveTo,
	METHOD_44_REQ_TransportTo,
	METHOD_45_REQ_TransportTo,
	METHOD_46_REQ_ShotStart,
	METHOD_47_REQ_ShotEnd,
	METHOD_48_REQ_RecoverShot,
	METHOD_49_REQ_AddShotYaw,
	METHOD_50_REQ_DelShotYaw,
	METHOD_51_REQ_DoSpellByID,
	METHOD_52_REQ_DoSpellByID,
	METHOD_53_REQ_DoSpellByID,
	METHOD_54_REQ_DoSpellByID,
	METHOD_55_REQ_CancelSpell,
	METHOD_56_REQ_DoDash,
	METHOD_57_REQ_StartFocus,
	METHOD_58_REQ_EndFocus,
	METHOD_59_REQ_SetHeroYaw,
	METHOD_60_REQ_NavigateTo,
	METHOD_61_REQ_NavigateTo,
	METHOD_62_REQ_InteractWithObject,
	METHOD_63_QuestAddNPC,
	METHOD_64_QuestDelNPC,
	METHOD_65_EnterStoryModel,
	METHOD_66_ExitStoryModel,
	METHOD_67_GetItems,
	SUP,
}
