using System;

public enum CellHeroClientMethod
{
	INF = GameUnitClientMethod.SUP,
	METHOD_0_OnBroadCastPing = INF,
	METHOD_1_MessageBox,
	METHOD_2_DebugMessage,
	METHOD_3_RollbackMove,
	METHOD_4_MoveLockACK,
	METHOD_5_OnWinShow,
	METHOD_6_OnLoseShow,
	METHOD_7_OnSpaceActionStart,
	METHOD_8_OnSpaceActionEnd,
	METHOD_9_CollectSpaceObject,
	METHOD_10_EnterSpaceObject,
	METHOD_11_OnNPCLoot,
	METHOD_12_OnNPCDie,
	METHOD_13_OnWaveLoaded,
	METHOD_14_OnMeleeWithoutTarget,
	SUP,
}
public enum CellHeroServerMethod
{
	INF = GameUnitServerMethod.SUP,
	METHOD_0_Exec = INF,
	METHOD_1_Exec,
	METHOD_2_BroadCastPing,
	METHOD_3_PrintDamage,
	METHOD_4_AddNPC,
	METHOD_5_AddNPC,
	METHOD_6_AddNPC,
	METHOD_7_AddNPCs,
	METHOD_8_AddNPCWithBirthPos,
	METHOD_9_DelRoundNPC,
	METHOD_10_AddObject,
	METHOD_11_AddObject,
	METHOD_12_AddObjects,
	METHOD_13_DelRoundObject,
	METHOD_14_UpdateProperty,
	METHOD_15_ModLevel,
	METHOD_16_ModXP,
	METHOD_17_RandomLevelEffect,
	METHOD_18_SelectLevelEffect,
	METHOD_19_ResetAI,
	METHOD_20_AIPause,
	METHOD_21_AIResume,
	METHOD_22_ResetSpell,
	METHOD_23_AddSpell,
	METHOD_24_SetupSpell,
	METHOD_25_SwapSpell,
	METHOD_26_TalkToNPC,
	METHOD_27_OpenFunctionUI,
	METHOD_28_SpaceActionStart,
	METHOD_29_SpaceActionEnd,
	METHOD_30_REQ_Revive,
	SUP,
}
