using System;

public enum GMAccountClientMethod
{
	INF = 0,
	METHOD_0_OnUpdatePlayerBaseInfo = INF,
	METHOD_1_OnUpdatePlayerBaseInfo,
	METHOD_2_OnUpdatePlayerDetail,
	METHOD_3_OnUpdateServer,
	METHOD_4_OnSQLResult,
	SUP,
}
public enum GMAccountServerMethod
{
	INF = 0,
	METHOD_0_DisplayServerList = INF,
	METHOD_1_DisplayPlayer,
	METHOD_2_FindPlayerByID,
	METHOD_3_FindPlayerByName,
	METHOD_4_FindPlayerByAccountID,
	METHOD_5_FindPlayerByAccountName,
	METHOD_6_OnNewDay,
	METHOD_7_ResetData,
	METHOD_8_ResetConstValue,
	METHOD_9_AddBoard,
	METHOD_10_AddBoard,
	METHOD_11_DelBoard,
	METHOD_12_AddNote,
	METHOD_13_DelNote,
	METHOD_14_SendMail,
	METHOD_15_ResetActivityTime,
	METHOD_16_OpenActivity,
	METHOD_17_CloseActivity,
	METHOD_18_ResetTimeBoard,
	METHOD_19_AddCDKey,
	METHOD_20_DisableIP,
	METHOD_21_DisableIP,
	METHOD_22_EnableIP,
	METHOD_23_DisableAccount,
	METHOD_24_DisableAccount,
	METHOD_25_EnableAccount,
	METHOD_26_AddGameFuncClosed,
	METHOD_27_DelGameFuncClosed,
	METHOD_28_ExecScript,
	METHOD_29_ExecScriptToPlayer,
	METHOD_30_PrintProperty,
	METHOD_31_PrintGlobalProperty,
	METHOD_32_SendMail,
	METHOD_33_ExecScriptToPlayer,
	METHOD_34_SQL_OnlineCount,
	METHOD_35_SQL_NewAccountCount,
	METHOD_36_SQL_RechargeAccountStatistic,
	METHOD_37_SQL_RechargeStatistic,
	METHOD_38_SQL_LoginCount,
	METHOD_39_SQL_NewRechargeAccountCount,
	METHOD_40_SQL_MaxAndAvgOnlineCount,
	METHOD_41_SQL_FindNameByNameAlias,
	METHOD_42_SQL_FindNameByNameAlias,
	SUP,
}
